---
- name: Install fonts
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FiraCode.zip
    dest: ~/.local/share/fonts/
    mode: "644"
- name: Unpack nerd-font
  ansible.builtin.unarchive:
    src: ~/.local/share/fonts/FiraCode.zip
    dest: ~/.local/share/fonts/
