---
- name: Set up the APT keyrings
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker to APT repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install latest version of Docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Ensure docker group exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Setup usergroup
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true
